id = "vscode-default-theme"
name = "VSCode Default Themes"
undefined
schema_version = 1
authors = ["ahetzm"]
description = "VSCode default themes converted for Zed."
repository = "https://github.com/ahetzm/zed-vscode-default-themes"
